import type { Metadata } from "next";
import { Poppins, Rammetto_One, Poor_Story, Grape_Nuts, Princess_Sofia } from "next/font/google";
import "./globals.css";

// Load local font
const poppins = Poppins({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

const rammetoOne = Rammetto_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-rammeto-one',
  display: "swap",
  adjustFontFallback: false,
});

const poorStory = Poor_Story({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poor-story',
  display: "swap",
  adjustFontFallback: false,
});

const grapeNuts = Grape_Nuts({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-grape-nuts',
  display: "swap",
  adjustFontFallback: false,
});
const princessSofia = Princess_Sofia({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-princess-sofia',
  display: "swap",
  adjustFontFallback: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${poppins.variable} 
      ${rammetoOne.variable} 
      ${poorStory.variable}
      ${grapeNuts.variable}
      ${princessSofia.variable}
      antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
