import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poor_Story } from 'next/font/google';
import localFont from 'next/font/local';
import "./globals.css";

// Load local font
const poorStory = localFont({
  src: './fonts/PoorStory-Regular.ttf',
  display: 'swap',
  variable: '--font-poor-story',
  weight: '400',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Geist({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poorStory.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
